### ISSUE TITLE
Random activation error

### ISSUE THREAD

**Issue by lvandal** [PaddleHQ/Mac-Framework-V4#25] opened 2018-10-01 14:32 UTC
A user yesterday contacted us because he wasn't able to activate his license. This error showed up:

<img width="532" alt="screen shot 2018-10-01 at 9 59 18 am" src="https://user-images.githubusercontent.com/157723/46293349-38307700-c561-11e8-8b02-8abfd2f9a1b4.png">

After a few tries, he was able to activate the license. I'm assuming this (not very useful) alert is shown by Paddle.

I ran through the same issue this morning as well using v4.0.3.

**Comment by GregularExpressions** [comment] 2018-10-01 14:45
Hey @lvandal 

Thanks for the report, we've already started working on this one as it was [reported](https://github.com/PaddleHQ/Mac-Framework-V4/issues/16) a little while ago.

We're making improvements to the error handling strategy in general, it's likely to be in the next release or so.

Thanks,
Greg.

**Comment by core-code** [comment] 2018-11-25 02:58
i guess this is a duplicate of  https://github.com/PaddleHQ/Mac-Framework-V4/issues/30 which was supposedly solved in 4.0.5?

**Closed** 2018-11-26 09:42 UTC
