### ISSUE TITLE
Paddle needs to send emails to all explaining Catalina bug + their license keys

### ISSUE THREAD

**Issue by tunabelly** [PaddleHQ/Mac-Framework-V4#73] opened 2019-10-02 14:41 UTC
Since all of us developers have been given 3 days notice from Paddle to either update to the newest V4 framework or migrate from V3->V4 for every app, **before** macOS Catalina is released, they need to step to the plate.

It's not realistic that we can all do this within 3 days, so I'm proposing that Paddle email everyone who's purchased a Mac app telling them that they regret the situation and wish that the developers could have had more time. Explain that updates are coming from all developers and that each app will need the license key re-entered after upgrading to Catalina. As a bonus, include their license keys so they don't have to email us if they can't find them.

**Comment by adriangranados** [comment] 2019-10-02 14:57
I didn't realize rumor says Catalina will be released October 4th. Paddle does need to step up and explain to all users what's going to happen when Catalina is out, especially for those apps still running V3. Not even releasing an app update with V4 right now give us sufficient time to ensure all users will install such updates before the release of Catalina.

**Comment by tunabelly** [comment] 2019-10-02 15:01
@adriangranados it does seem it may ship this week, as in tomorrow October 4th.

https://www.techradar.com/news/macos-catalina
https://www.cnet.com/how-to/macos-catalina-may-ship-this-week-get-ready-now/

**Comment by rishimodha** [comment] 2019-10-02 15:07
This is extremely urgent. We are going to get literally thousands and thousands of support tickets.

**Comment by tunabelly** [comment] 2019-10-02 15:28
@rishimodha we're also about to get thousands of angry support tickets about how their apps "stopped working" and the only fix is to enter a license key or purchase a new one. This is probably the worst possible situation we could be in.

**Comment by rishimodha** [comment] 2019-10-02 15:29
I've raised the issue with Harrison. Hopefully, we'll get a response from him soon.

**Comment by tunabelly** [comment] 2019-10-02 17:02
@rishimodha thanks for raising it with Harrison. Please let us all know how that goes.

From what Paddle has said, the only way they are providing to fix this is to update all apps to use 4.0.13 and get users to update before installing Catalina.

**Comment by rishimodha** [comment] 2019-10-02 17:06
> @rishimodha thanks for raising it with Harrison. Please let us all know how that goes.
> 
> From what Paddle has said, the only way they are providing to fix this is to update all apps to use 4.0.13 and get users to update before installing Catalina.

If this is what they wanted, they should have given WAY more notice. No way it's possible to update 20+ apps and TEST within the next few days. They need to provide a fix on the v3 SDK, which I believe many developers are still using.

**Comment by tunabelly** [comment] 2019-10-02 17:12
@rishimodha I agree with you 100%. This is why I'm so upset that we're in this situation with the only option from Paddle being to update all our apps to V4.

If they do provide an update for V3 with this change, I would be ok with that, even though the time frame is still really, really short. However, I'm not holding my breath for that to happen so I'm making contingency plans to try to handle this incredibly crappy situation we're now in.

**Comment by rishimodha** [comment] 2019-10-02 17:16
@tunabelly I personally don't think it's a big ask to get v3 patched - i'm sure it can be done within a day or two if they dedicate dev time to getting it done. It will be very shortsighted of Paddle not to take these concerns seriously.

**Comment by tunabelly** [comment] 2019-10-03 00:40
@rishimodha I also agree with this, that it's not a big ask at all considering there are still many, many apps on V3.

**Comment by Iomegan** [comment] 2019-10-04 15:43
> I wanted to follow up on this topic, as we've given out incorrect information to you, for which I can only apologise. Version 3 of our SDK is not affected by the NSData changes which are coming with Catalina. Applications which have been developed with v3 of our SDK will work just fine when customers upgrade to Catalina and their activated license state will remain intact, so they will not be prompted to re-enter their license information.

_Originally posted by @kwokaaron in https://github.com/PaddleHQ/Mac-Framework/issues/230#issuecomment-538349543_

**Comment by core-code** [comment] 2019-10-07 20:13
can we have some actual confirmation whether this issue only affects *some* or *all* customers that upgrade to Catalina?

**Comment by kwokaaron** [comment] 2019-10-08 09:43
@core-code v3 is not affected by this NSData license activation issue. However, I strongly recommend upgrading as soon as you have the resource to as v3 is nearing its end-of-life support.

**Comment by core-code** [comment] 2019-10-08 09:58
@kwokaaron i saw above that v3 is not affected, thanks. i was asking whether all of our customers will be affected - we are using v4. when i read the release-notes to Paddle v4.0.13 the mentioned entry regarding Catalina looked totally innocent, like maybe one in thousand customers would hit that - so we didn't take any action. i think thats quite a bad miscommunication from 'Paddle'. in addition to all the timing issues that people have already complained about, this is probably the worst thing. we should have been alerted that immediate action is required. and now we get customer complaints every few minutes...

**Comment by core-code** [comment] 2019-10-08 10:00
whats worse, some customers can not re-enter their existing license, because they are hitting the activation limit. shouldn't re-activating on the very same Mac never use an additional activation, but always re-use the existing activation?

**Comment by rishimodha** [comment] 2019-10-08 10:01
@core-code exactly, the sdk isn't able to even tell that a specific Mac already has a license assigned to it and reuse that same activation allowance.

**Comment by core-code** [comment] 2019-10-08 11:31
we've released a hotfix containing 'Paddle v4.0.13' on an extremely tight schedule, but it seems it didn't help at all.

after reading https://github.com/PaddleHQ/Mac-Framework/issues/230#issuecomment-537103601 it seemed like updating to 4.0.13 is enough if you do it *before* a user has updated to Catalina. however, it seems this does just nothing if the mentioned change related to /verifyActivation/ is not done too. bah, more awful miscommunication.

**Comment by JoMarques09** [comment] 2019-10-08 12:35
Hi @core-code  

Sorry, the release notes were not clear enough this has now been changed, you should have also got a detailed email for the released that made this clearer similar to what is in PaddleHQ/Mac-Framework#230 (comment). But essentially all users will be affected if their app does not have v4.0.13. 
Regarding the activation limit, the license activations should not count as it's the same machine. Could you send us the licenses where this happens to help@paddle.com so we can investigate?

Many Thanks,
Joana

**Comment by core-code** [comment] 2019-10-08 12:36
will do

**Comment by rishimodha** [comment] 2019-10-08 13:34
@kwokaaron just got another user that had their app license reset when updating to Catalina. The same license could not be reused on the same Mac. I am emailing to help@paddle.com the license key. 

There clearly seems to be some issue with the v3 SDK and users updating to Catalina. We have now got 5 users complain of this same issue in less than 24 hours.

**Comment by JoMarques09** [comment] 2019-10-08 14:42
@core-code @rishimodha 

Sorry, I gave you the wrong email, can you send those to sellers@paddle.com instead?

Many Thanks,
Joana

**Comment by core-code** [comment] 2019-10-08 15:08
actually no. getting customers to send files from their Mac is a lot of work and we aren't going to do that. we had more than enough additional work due to your complete fuckup on this Catalina matter. 

we will just refer any customer with any activation issue to help@paddle.com and i fully expect you to find out about, and fix the issue with the used-up activations yourself.

**Comment by GaryMcGrathUK** [comment] 2019-10-08 16:28
@core-code I am stepping in here for Joana. I appreciate that the current issue you are experiencing with version 3 of our SDK is frustrating, but I would ask that you remain civil in your communications with us, Paddle will not tolerate abusive language towards our staff. 

With that said, what we know so far is that the licenses we’ve been provided have shown that a different UUID has been passed to Paddle for the license activations, so our SDK is correctly prompting again for activation. We are still investigating why we’re being sent a different UUID, as this should only happen if the Mac itself physically changed. This also means that although the outcome might be the same ( in terms of license prompt on upgrade ), this issue is completely separate to our NSData fixes for v4. 

You can of course rely on our order support team to handle reactivations of your application to help customers get back up and running. 

Regards,

Gary

**Comment by core-code** [comment] 2019-10-08 16:41
>  I am stepping in here for Joana. I appreciate that the current issue you are experiencing with version 3 of our SDK is frustrating, 

in all my messages i've talked  about v4 of the framework. AFAIK the Catalina issue doesn't affect v3. we are using v4 in our most important product.

> but I would ask that you remain civil in your communications with us, Paddle will not tolerate abusive language towards our staff.

huh? i'm am not aware of any 'abusive' language. i think the term 'fuckup' is a generally accepted term to describe messing things up in a big way. if you disagree i'd be happy to use any euphemism you like. though i think we should focus on the issue at hand instead of wasting time by agreeing on proper euphemisms.

> different UUID has been passed to Paddle for the license activations

i think we have two different issues here:
1.) the initially described issue where a user upgrading to 'Catalina' will loose his activation and needs to manually re-activate. this is urgent for us, since we already received a dozen complains, and are sure to get many hundreds more. we've already shipped two hot-fixes using your 4.0.13 framework but are unable to get it to work as your workaround doesn't stick. i've describes the problem in issue #230 . this is urgent and i'd need a fix from you here in the next minutes!

2.) the additional  issue mentioned in this thread where a user that manually re-activates his license will use-up another activation and may therefore hit the activation limit. i hope you'll investigate this but this is not as urgent for us as it hits just a portion of the user-base.

**Comment by core-code** [comment] 2019-10-08 16:47
> With that said, what we know so far is that the licenses we’ve been provided have shown that a different UUID has been passed to Paddle for the license activations, so our SDK is correctly prompting again for activation. 

ok i see that both issues might be intermingled. if Paddle determines a different UDID for the same Mac under Catalina, i guess that calling 'verifyActivation' on launch will not result in the license being accepted? if so, this is not the issue we are seeing on a test Mac, where we are completely unable to bring over the activation from Mojave even with the 4.0.13+"verifyActivation Once" fix

**Comment by rishimodha** [comment] 2019-10-08 16:51
Does anyone know if Apple may have changed how the UUID is reported in Catalina vs Mojave? We have a few users insisting that their license key is being rejected after updating to Catalina on the SAME Mac, with the reason being that the activation limit has been hit (despite the Mac running the licensed app prior to them updating to Catalina).

**Comment by GaryMcGrathUK** [comment] 2019-10-08 17:05
@core-code @rishimodha We have confirmed that both our v3 and v4 SDK's are seeing different UUID's presented to them after updating to Catalina. ( It should also be noted that this does not seem to be affecting all upgrades to Catalina ). Our developers are currently investigating to try and get to the bottom of this.

**Comment by GaryMcGrathUK** [comment] 2019-10-08 17:07
> if so, this is not the issue we are seeing on a test Mac, where we are completely unable to bring over the activation from Mojave even with the 4.0.13+"verifyActivation Once" fix

Can you take this conversation to sellers@paddle.com please @core-code as we need to see the code you've used to implement this

**Comment by rishimodha** [comment] 2019-10-08 17:07
@GaryMcGrathUK hmm that's what I suspected. I think side by side, we may have to get your team to look into increasing the activation limit of all our customers to prevent thousands of support emails. Are you able to do a mass edit, to change the limit e.g. from 3 to 6 per license?

**Comment by JoMarques09** [comment] 2019-10-08 17:19
@rishimodha We can definitely do that for you, I'll get the developers to increase the activations limit from 3 to 6 first thing in the morning. If you wish we can do this for you as well @core-code.

**Comment by rishimodha** [comment] 2019-10-08 17:21
@JoMarques09 thanks, please do this because the last thing we want is to inconvenience our customers with activation limit errors after they update to Catalina.

**Comment by core-code** [comment] 2019-10-08 17:35
@JoMarques09 yes please increase from 5 to 6 so that the additional activation can't possibly hit the limit

**Comment by tunabelly** [comment] 2019-10-08 17:39
@JoMarques09 please do this for our customers as well since we have quite a few from our apps using Paddle.

**Comment by rishimodha** [comment] 2019-10-08 17:41
@tunabelly I was wondering when we'd hear from you. Are you getting support emails about this like we are?

**Comment by Iomegan** [comment] 2019-10-08 17:43
@JoMarques09 are you increasing the activation number by one ore are you setting all of them to a certain value?

**Comment by rishimodha** [comment] 2019-10-08 17:44
@Iomegan In our case, i've requested that they be doubled from whatever each license is set to.

**Comment by tunabelly** [comment] 2019-10-08 18:32
@rishimodha surprisingly no not so far. I've been waiting for the storm and so far nothing. It's possible that over the next few days we'll have a whole bunch. I'll keep you guys updated if it changes. FYI we're using Paddle 3.0.40 in all our apps so maybe that helps?

**Comment by Iomegan** [comment] 2019-10-08 18:38
I only had one user who said:  

> I upgraded to Catalina and now its expired.

Would have been buch more if it was an issue affecting every upgrade.

**Comment by zcohan** [comment] 2019-10-08 22:36
I'm also receiving a ton of email from confused customers upgrading to 10.15 losing their registration state. I made an incorrect assumption (based on Paddle's email last week) that the manual call to verifyActivation on 10.15 need happen only once (in order to migrate the license permanently to the new format). It seems that it must be called every launch on 10.15, which is fairly fragile (disabling an internet connection, for example, will prevent the activation from going through). It's a disappointing and frustrating situation for my customers and for me. I reported the issue with the SDK to Paddle back in early September when it came up during my own 10.15 testing. At that point Catalina had been available as a developer beta for 3 months. To me it seems like there was enough time to get on top of the issue, with the right resources applied to the problem and vigilance towards new macOS releases. One wonders if it is indicative of the general direction Paddle is moving as a company, i.e. away from supporting independent Mac developers, and more towards subscription-based web apps.

**Comment by JoMarques09** [comment] 2019-10-09 09:36
> @JoMarques09 are you increasing the activation number by one ore are you setting all of them to a certain value?
@Iomegan we can increase the limit by one or set it all to certain value. Which one do you prefer?

**Comment by Iomegan** [comment] 2019-10-09 09:55
Thanks, please let it as it is for now.

**Comment by JoMarques09** [comment] 2019-10-09 10:01
@zcohan  In order to help you we need to have a look at the code you used to implement this, would you be able to send that to sellers@paddle.com and mention my name?

**Comment by zcohan** [comment] 2019-10-09 10:18
@JoMarques09 Yeah I sent an email to sellers@paddle.com yesterday with the specific details of my implementation. Would also appreciate automatically doubling the activation limit for all licenses just in case.

**Comment by core-code** [comment] 2019-10-09 12:34
> It seems that it must be called every launch on 10.15, which is fairly fragile
> (disabling an internet connection, for example, will prevent the activation from going through).

this is exactly what we are seeing too. and it isn't a solution in any case. the only way for people on Catalina to have a permanently working activation is if they have entered it manually, so far there doesn't seem to be any reliable way to 'bring it over' from Mojave or earlier.

**Comment by JoMarques09** [comment] 2019-10-09 15:53
@core-code @zcohan @tunabelly and @rishimodha the activation number for your licenses have now been increased.   
Will follow up as soon as we know more about the root cause of this issue.

**Comment by core-code** [comment] 2019-10-09 15:58
thanks

**Comment by OskarGroth** [comment] 2019-10-12 12:12
Seriously, does Paddle have anyone running the ship over there these days? How is it that Catalina has time to go public before you realise that your SDK is completely broken? Respectable software companies would have their engineers download the Beta and start working on fixes back in June.

I couldn't believe it when I got the email saying "We have increased the number of activations for all end users who didn’t previously have any remaining. This way they can activate normally after installing Catalina without contacting your support team.". Do you seriously not realise what an extreme hack of a temporary solution this is? Not to mention corroding the trust between Paddle and Merchants as you tamper with their activation limits to solve your own front-end bugs?

That together with "Could you send us the licenses where this happens to..." is stuff I'd expect from a small indie or hobbyist operation. Not a big company like Paddle, that should:

1. Treat an issue like this as a 🔥 and pull all strings necessary to resolve it within 24h.
2. Prioritise QA engineering and 100% test coverage so you don't end up here in the first place.

This together with shutting down DevMate has me seriously questioning my future with Paddle, after being a merchant since 2015.

**Comment by core-code** [comment] 2019-10-12 12:38
> Seriously, does Paddle have anyone running the ship over there these days?

couldn't agree more. meanwhile the "other side" of Paddle, their helpdesk/customersupport is also completely broken, see here: https://github.com/PaddleHQ/Mac-Framework/issues/143#issuecomment-540550429

**Comment by GaryMcGrathUK** [comment] 2019-10-14 11:15
Hi all,

Just wanted to drop and update on some of the concerns raised here. We are still trying to replicate the issue on our internal machines, we’ve conducted 100’s of updates to Catalina over the past few months and we’ve not encountered this issue. Therefore the only option we have to shed more light onto the situation is to get details from people who have experienced the problem.

We completely understand that increasing the number of activations is a temporary solution. Our stats suggested that over the coming week, we would have over 50,000 customers who’d run into the activation problem and would get stuck, without any option but to contact support teams. Because we are still investigating the issue, we knew it would not be resolved for these customers in time, so we took the decision to help those customers ( and by extension the support teams of sellers ) and ensure they could self serve past the problem. We do have a record of the customers we’ve increased activations for and will be circling back to fix the activation count at a later date.

I appreciate that the ongoing issues we are looking into are frustrating for sellers and customers alike, but GitHub is not the place to raise these concerns as only our developers are looking at GitHub and we’d rather they remain focused on resolving the outstanding problems. I am closing this thread,  If you would like to discuss this any further, please raise a conversation with us at sellers@paddle.com and we’ll do our best to answer any questions you have. 

Kind regards,

Gary

**Closed by GaryMcGrathUK** 2019-10-14 11:15 UTC
